Repository graphql/graphql.github.io, pull requests merged in 2020-11, with the labels that each got.

#937 Fix fragment name
  src/content/learn/Learn-Schema.md
Labels: ✏️ Editorial

#921 Adds a section for Elixir clients
  src/content/code/code.md
Labels: ✏️ Editorial

#890 Add Morpheus GraphQL to the list of GraphQL libraries
  src/content/code/code.md
Labels: ✏️ Editorial

#917 Fix wrong meaning in "thinking in graphs - legacy"
  src/content/learn/BestPractice-ThinkingInGraphs.md
Labels: ✏️ Editorial

#949 Added Graphpinator
  src/content/code/code.md
Labels: ✏️ Editorial

#945 added NGraphQL link
  src/content/code/code.md
Labels: ✏️ Editorial

#679 A link to the graphql implementation in D
  src/content/code/code.md
Labels: ✏️ Editorial

#909 Added "GraphQL API for WordPress" on the PHP list
  src/content/code/code.md
Labels: ✏️ Editorial

#902 Added KGraphQL to the Kotlin list
  src/content/code/code.md
Labels: ✏️ Editorial

#943 Add answers for initial FAQ
  src/content/faq/General.md
Labels: 💬 FAQ

#942 Create Frequently Asked Questions (FAQ) Page
  src/assets/css/_css/docs.less
  src/components/FAQLayout/index.tsx
  src/components/HeaderLinks/index.tsx
  src/content/faq/General.md
  src/templates/doc.tsx
Labels: 💬 FAQ

#957 Set min-height on header to fix responsiveness
  src/assets/css/_css/graphql.less
Labels: 🎨 Design, 🐛 Bug

#969 Update documentation for urql
  src/content/code/language-support/javascript/client/urql.md
Labels: ✏️ Editorial

#968 Fix issues in initial FAQ based on feedback
  src/content/faq/General.md
Labels: 💬 FAQ

#970 Add contributing guide
  CONTRIBUTING.md
  README.md
Labels: ⚙️ Meta

#979 Update README.md
  README.md
Labels: ⚙️ Meta

#976 Re-add NGraphQL link in Code page (for .NET)
  src/content/code/language-support/c-net/server/ngraphql.md
Labels: ✏️ Editorial
