Repository graphql/graphql.github.io, pull requests merged in 2020-12, with the labels that each got.

#980 Update contributing guidelines for Code page
  CONTRIBUTING.md
Labels: ⚙️ Meta

#988 Add mu-haskell as another Haskell GraphQL Server alternative! 🚀
  src/content/code/language-support/haskell/server/mu-haskell.md
Labels: ✏️ Editorial

#990 Add graphql-hooks client library
  src/content/code/language-support/javascript/client/graphql-hooks.md
Labels: ✏️ Editorial

#987 Update contributing guide to include browser support
  CONTRIBUTING.md
Labels: ⚙️ Meta

#977 Add issue and pull request templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/code-changes.md
  .github/ISSUE_TEMPLATE/new-faq-question.md
  .github/ISSUE_TEMPLATE/question.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ⚙️ Meta

#982 Curate new FAQ sections and add more answers
  src/components/FAQLayout/index.tsx
  src/content/faq/General.md
  src/templates/doc.tsx
Labels: 💬 FAQ

#985 Implement new accordion design for FAQ page
  src/assets/css/_css/docs.less
  src/assets/css/_css/faq.less
  src/assets/css/style.less
  src/components/FAQLayout/index.tsx
  src/components/FAQSection/index.tsx
  src/content/faq/BestPractices.md
  src/content/faq/Frontend.md
  src/content/faq/General.md
  src/content/faq/GettingStarted.md
  src/content/faq/Specification.md
  src/pages/faq.tsx
  src/templates/doc.tsx
  src/utils/useFAQAccordion.ts
Labels: 🎨 Design, 💬 FAQ
