Repository graphql/graphql.github.io, pull requests merged in 2022-11, with the labels that each got.

#1274 Prevent translation of code blocks by wrapping them in <code> tag
  src/components/Prism/index.tsx
Labels: 💄 Enhancement

#1276 Remove https from localhost based link name
  src/content/graphql-js/Tutorial-ExpressGraphQL.md
Labels: ✏️ Editorial

#1272 fix: updated broken link to kotlin server docs
  src/content/code/language-support/java-kotlin-android/server/graphql-kotlin.md
Labels: 🐛 Bug

#1267 Add Escape.tech – GraphQL Security, GraphQL.Security & GraphQL Armor
  src/content/code/services/escape.md
  src/content/code/services/graphql.security.md
  src/content/code/tools/graphql-armor.md
Labels: ✏️ Editorial
